blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name = "Home"),
    path('movies/', views.movies, name = "Movies"),
    path('movies/<int:pk>/', views.moviesdetail,name='MoviesDetail'),
    path('directors/', views.directors,name="Directors"),
    path('directors/<int:pk>', views.directorsdetail,name="DirectorsDetail"),
    path('actors/', views.actors, name = "Actors"),
    path('actors/<int:pk>/', views.actorsdetail,name='ActorsDetail'),
    path('login/', views.login_user , name = "Login"),
    path('logout/', views.logout_user , name = "Logout"),
    path('register/', views.register_user, name = "Register"),
    path('suggest/', views.contact, name = "Suggest"),
    path('profile/', views.profile, name = "Profile"),
    # path('api/v1/movie', views.movie_collection),
    # path('api/v1/director', views.director_collection),
    # path('api/v1/actor', views.actor_collection),
]

movies/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 
from blog.views import general

urlpatterns = [
    path('',general),
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls'))
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blog/models.py
# models built in
from django.contrib.auth.models import User
from django.db import models

#django utils
from django.db.models.signals import post_save
from django.dispatch import receiver

#python std
import datetime

#width 150 px , height 200px

@receiver(post_save, sender=User)
def create_profile(sender, instance, created, **kwargs):
    if created:
        user_profile = Profile(user=instance)
        user_profile.save()

class Profile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    genres = models.ManyToManyField("Genre", blank=True)
    actors = models.ManyToManyField("Actor", blank=True)
    directors = models.ManyToManyField("Director", blank=True)
    movies = models.ManyToManyField("Movie", blank=True)

    def __str__(self):
        return self.user.username

class Actor(models.Model):

    name = models.CharField(max_length=50,blank=True)
    review = models.TextField(default = "",blank=True)
    image = models.ImageField(upload_to='actor_image',blank=True,default="actor_image/ProfilePic.png",null=True)
    reference_image = models.URLField(max_length=200, default = "", blank=True)
    reference_description = models.URLField(max_length=200, default = "",blank=True)
 
    def __str__(self):
        return self.name

class Director(models.Model):

    name = models.CharField(max_length=50,blank=True)
    image = models.ImageField(upload_to="director_image",default="actor_image/ProfilePic.png",blank=True)
    review = models.TextField(default = "",blank=True)
    reference_image = models.URLField(max_length=200, default = "",blank=True)
    reference_description = models.URLField(max_length=200, default = "",blank=True)

    def __str__(self):
        return self.name

class Genre(models.Model):
    
    name = models.CharField(default="Non Genre",max_length=100,blank=True)

    def __str__(self):
        return self.name

class Rating(models.Model):
    
    name = models.CharField(default=0,max_length=100,blank=True)

    @property
    def rating(self):
        return {
            "NR" : "Not Rated",
            "G" : "General Audiences",
            "PG" : "Parental Guidance Suggested",
            "PG-13" : "Parents Strongly Cautioned",
            "R" : "Restricted",
            "NC-17" : "Adults Only"
        }[self.name]

    def __str__(self):
        return self.name

class Actor_Movie(models.Model):
    
    actor = models.ForeignKey(Actor, on_delete=models.CASCADE,blank=True) 
    movie = models.OneToOneField("Movie", on_delete=models.CASCADE,blank=True)
    
    role = models.CharField(max_length=50,default = "",choices=[
        ("Leading Actor","Leading Actor"),
        ("Leading Actress","Leading Actress"),
        ("Supporting Actor","Supporting Actor"),
        ("Supporting Actress","Supporting Actress")
    ],blank=True)

    time_in_movie = models.IntegerField(default=0,blank=True)
    physical_aspect = models.IntegerField(default=0,blank=True)

    def __str__(self):
        return '|'.join([self.actor.name,self.movie.name,self.role]) 

class Character_Movie(models.Model):

    name = models.CharField(max_length=50,blank=True,default = "")
    actor = models.OneToOneField(Actor,on_delete=models.CASCADE,blank=True)
    movie = models.ForeignKey("Movie",on_delete=models.CASCADE,blank=True)

    def __str__(self):
        return self.name

class Scene_Movie(models.Model):

    image = models.ImageField(upload_to = "scenes_images",blank=True)
    description = models.CharField(max_length=100,blank=True,default = "")
    movie = models.ForeignKey("Movie",on_delete=models.CASCADE,blank=True)
    caption = models.TextField(default = "",blank=True)

    reference_image = models.URLField(max_length=200, default = "")

    def __str__(self):
        return '|'.join([self.description,self.movie.name]) 

class Quote_Movie(models.Model):

    quote = models.CharField(max_length=100,default = "", blank=True)
    movie = models.ForeignKey("Movie",on_delete=models.CASCADE,blank=True)
    character = models.OneToOneField(Character_Movie,on_delete=models.CASCADE,blank=True)
    description = models.TextField(default = "",blank=True)

    @property
    def actor(self):
        return self.character.actor.name

    def __str__(self):
        return '|'.join([self.character.name,self.movie.name])

def get_default_rating_result():
    """ get a default value for result status; create new result if not available """
    return Rating.objects.get_or_create(name="not_rated")[0].id

class Movie(models.Model): 

    name = models.CharField(max_length=50,blank=True)
    release_date = models.DateField(blank=True)
    duration = models.IntegerField(default=0,blank=True)
    image = models.ImageField(upload_to="movie_image",blank=True,default = "actor_image/ProfilePic.png")
    language = models.CharField(default = "", max_length=40,blank=True)
    sinopsis = models.TextField(default = "",blank=True)
    review = models.TextField(default = "",blank=True)
    review_date = models.DateField(blank=True, default = datetime.date.today)
    

    reference_image = models.URLField(max_length=200, default = "",blank=True)
    reference_description = models.URLField(max_length=200, default = "",blank=True)

    director = models.ForeignKey(Director,on_delete=models.CASCADE,blank=True)
    rating = models.ForeignKey(Rating,on_delete=models.CASCADE,default=get_default_rating_result,blank=True)

    genres = models.ManyToManyField(Genre,blank=True)
    actors = models.ManyToManyField(Actor, related_name="movies",blank=True)

    #score fields 
    cinematography = models.FloatField(default=0,blank=True)
    acting = models.FloatField(default=0,blank=True)
    editing = models.FloatField(default=0,blank=True)
    custom = models.FloatField(default=0,blank=True)
    music = models.FloatField(default=0,blank=True)
    screenplay = models.FloatField(default=0,blank=True)

    #other pages score
    rotten_tomatoes = models.FloatField(default=0,blank=True)
    imdb = models.FloatField(default=0,blank=True)

    def scores_json(self):
        return dict(
            Cinematography = self.cinematography,
            Acting = self.acting,
            Editing = self.editing,
            Custom = self.custom,
            Music = self.music,
            Screenplay = self.screenplay
        )

    def icons_scores_json(self):
        return dict(
            Our = self.final_score,
            RottenTomatoes = self.rotten_tomatoes,
            Imdb = self.imdb,
        )
        
    @property
    def final_score(self):
        scores_dict = self.scores_json()
        total_fields = len(scores_dict.items())
        sum = 0
        for field , score in scores_dict.items():
            sum += score
        average = sum/total_fields
        return round(average,2)

    @property
    def only_year(self):
        return self.release_date.strftime("%Y")

    def __str__(self):
        return self.name

blog/templates/blog/Home.html
{% extends "blog/header.html" %}
{% load static %}

{% block styles %}

    {{ block.super }}   

    <style>
        #parent{width: 100%;}
    </style>
{% endblock %}

{% block content %}

<div id = "webpage">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id = "header">
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home' %}">
                <button type="button" class="btn btn-primary position-relative">
                    Home
                </button>
            </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Movies' %}">
                <button type="button" class="btn btn-light position-relative">
                    Movies
                </button>
            </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Directors' %}">
                    <button type="button" class="btn btn-light position-relative">
                        Directors
                    </button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Actors' %}">
                    <button type="button" class="btn btn-light position-relative">
                        Actors
                    </button>
                </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <button type="button" class="btn btn-info position-relative">
                    Account
                </button>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                {% if user.username != "" %}
                    <li><a class="dropdown-item" href="{% url 'Profile' %}">{{ user.username }}</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'Register' %}">Register</a></li>
                    <li><a class="dropdown-item" href="{% url 'Login' %}">Login</a></li>
                {% endif %}
              </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Suggest' %}">
                    <button type="button" class="btn btn-warning position-relative">
                        Suggest
                    </button>
                </a>
            </li>
          </ul>
          <!-- <form class="d-flex">
            <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
        </div>
    </nav>

    <div id = "page">

        <div id = "parent">

            <div class = "section_separator">
                INFORMATION
            </div>
            <br>

            <div>
                <div class="p-3 mb-2 bg-dark" style = "text-align: center;"><h3 class="text-light">Welcome to Sergio's library!</h3></div>
                <p>
                    Here you will find reviews and opinions for movies, actors and directors.
                    This page is divided in three sections: Movies, Actors and Directors. In each one
                    you can filter by Release date, or by Genre and Alphabetical order. The point is that
                    this library is organizad so you can navigate through easily.
                    
                    <ul>
                        <li class="badge badge-info">Objetive</li>
                        <ul>
                            <li>
                            Give a rigorous and detailed reviews in form of essays about 600 to 1000 words. Not just 
                            like a review briefing
                            </li>
                            <li>
                                Being pure objetive
                            </li>
                            <li>
                                A quantiative view of rating movies and acting. Giving scores to some aspects in the movie,
                                basicaly the ones who are considered in the Oscars such as cinematography, music, screenplay ,etc.
                            </li>
                            <li>
                                To rate actors is kind of different it is measured in a specific way it is possible to capture and for instance
                                give a precise score to the acting. A lot comes from the idea of being more strict if the actor has more
                                time on screen.
                            </li>
                        </ul>
                        <li class="badge badge-info">Vision</li>
                        <ul>
                            <li>This is not going to be a page like rotten tomatoes or imdb</li>
                            <li>This page will last until i get tired of watching movies and tired of rating</li>
                            <li>I want to fill the database with more movies and reviews</li>
                            <li>I will want the opinion of other people on my reviews and ratings</li>
                        </ul>
                        <li class="badge badge-warning">Important Considerations</li>
                        <ul>
                            <li>Every review at the end of the day is just my opinion but i will try to empathize with every perspective
                                so i can give a more precised review without lacking of details and not abusing of generality.
                            </li>
                            <li>
                                The scores for acting and movies also will come from my opinion. But at least for acting there will be some calculus 
                                behind to give a precise score. Obviously i will accept discuss of the calculus behind if some don't agree.
                            </li>
                            <li>Every picture or score is taken from another websites for instance the link or reference to those sources are included</li>
                        </ul>
                    </ul>
                </p>
            </div>
        </div>
    </div>

    <div id = "bottom" class = "bg-dark">
    </div> 
</div>

{% endblock %}

{% block scripts %}

{% endblock %}

blog/templates/blog/actorsdetail.html
{% extends "blog/header.html" %}
{% load static %}
{% block styles %}
    
    {{ block.super }}

    <style>
        a{ text-decoration: none;color :black}

        td
        {
            border-top: 1px solid black;
            text-align: center;
            
        }
        td:hover
        {
            background-color: var(--nav-color);
            color: white;
        }

        td a:hover
        {
            background-color: var(--nav-color);
            color: white;
        }

        thead th
        {
            background-color: var(--page-color);
            color: white;
        }

        table { border-spacing:0 }

        #section_information
        {
            display: grid;
            grid-template-columns: 70% 30%;
            column-gap: 3%;

        }

        #right_side {width: 40%;}
        #parent {width: 100%;}
        .movies
        {
            display:flex;
            justify-content: space-evenly;
            column-gap: 5%;
            row-gap: 20px;
            flex-basis: 50%;
            flex-wrap: wrap;
            flex-direction: row;
            margin-top: 5%;
        }   
    </style>
{% endblock %}

{% block content %}

<div id = "webpage">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id = "header">
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home' %}">
                <button type="button" class="btn btn-light position-relative">
                    Home
                </button>
            </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Movies' %}">
                <button type="button" class="btn btn-light position-relative">
                    Movies
                </button>
            </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Directors' %}">
                    <button type="button" class="btn btn-light position-relative">
                        Directors
                    </button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Actors' %}">
                    <button type="button" class="btn btn-primary position-relative">
                        Actors
                    </button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#section_name">
                    <button type="button" class="btn btn-secondary position-relative">
                        {{ actor.name }}
                    </button>
                </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <button type="button" class="btn btn-info position-relative">
                    Account
                </button>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                {% if user.username != "" %}
                    <li><a class="dropdown-item" href="{% url 'Profile' %}">{{ user.username }}</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'Register' %}">Register</a></li>
                    <li><a class="dropdown-item" href="{% url 'Login' %}">Login</a></li>
                {% endif %}
              </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Suggest' %}">
                    <button type="button" class="btn btn-warning position-relative">
                        Suggest
                    </button>
                </a>
            </li>
          </ul>
        </div>
    </nav>

    <div id = "section_name">
        {{ actor.name }}
    </div>
    <br>

    <div id = "page">

        <div id = "right_side">
    
            <div class = "section_separator">
                MOVIES
            </div>

            <div class = "movies">
                {% for movie in actor.movie_set.all %}
                    <div class = "images" style = "width: 30%;height: auto;">
                        <a href = "{% url 'MoviesDetail' movie.id %}" target = "_blank">
                            <img src="{{ movie.image.url }}" style="width: 100%; height: auto"> 
                        </a>
                        <figcaption style = "text-align: center;"> {{ movie.name }} </figcaption>
                    </div>
                {% endfor %}
            </div>
            
        </div>

        <div id = "parent">

            <div class = "section_separator">
                INFORMATION
            </div>
            <br>

            <div id = "section_information">

                <div style = "display: flex;align-items: center;">
                    {{ actor.review }}
                </div>

                <div class = "images" style = "width: 70%;height: auto">
                    <img src="{{ actor.image.url }}" style="width: 100%;height: auto">
                    <figcaption style = "text-align: center;"> {{ actor.name }} </figcaption>
                </div>

            </div>
            <br>

            <div class = "section_separator">
                STATISTICS
            </div>
            <br>

            <div>
                <table class = "table" style = "width: 100%;">
                    <thead>
                        <form method = "POST">{% csrf_token %}
                            <th style = "text-align: center;">Year<input name = "Year" type = "checkbox"></th>
                            <th style = "text-align: center;">Movies<input name = "Movie" type = "checkbox"></th>
                            <th style = "text-align: center;">Our Score<input name = "Our_score" type = "checkbox"></th>
                            <th style = "text-align: center;">Rotten Tomatoes<input name = "Rotten" type = "checkbox"></th>
                            <th style = "text-align: center;">Imdb<input name = "imdb" type = "checkbox"></th>
                        </form>
                    </thead>
                    <tbody>
                        {% for movie in movie_list %}
                            <tr>
                                <td>{{ movie.only_year }}</td>
                                <td><a href = "{% url 'MoviesDetail' movie.id %}">{{ movie.name }}</a></td>
                                <td>{{ movie.final_score }}</td>
                                <td>{{ movie.rotten_tomatoes }}</td>
                                <td>{{ movie.imdb }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <br>
        </div>
    </div>

    <div id = "bottom" class = "bg-dark">
    </div> 
</div>
{% endblock %}

{% block scripts %}

{{ applied_filters|json_script:'applied_filters' }}
<script src = "{% static 'blog/js/jquery.js' %}"></script>
<script>
   
    var applied_filters = jQuery.parseJSON($("#applied_filters").text())
    var inputs = $("input");

    console.log(applied_filters)

    for (input of inputs)
    {
        for (filter of applied_filters)
        {
            if (input.name == filter)
            {
                console.log(input.name)
                $(input).prop("checked",true)
            }else{
                $(input).css("display","None")
            }
        }
    }

    for (input of inputs)
    {
        $(input).change(function(){
            console.log(this.name)
            this.form.submit()
        })
    } 
    
    
</script>

{% endblock %}

blog/templates/blog/directorsdetail.html
{% extends "blog/header.html" %}
{% load static %}
{% block styles %}
    
    {{ block.super }}

    <style>

        a{ text-decoration: none;color :black}

        td
        {
            border-top: 1px solid black;
            text-align: center;
            
        }
        td:hover
        {
            background-color: var(--nav-color);
            color: white;
        }

        td a:hover
        {
            background-color: var(--nav-color);
            color: white;
        }

        thead th
        {
            background-color: var(--page-color);
            color: white;
        }

        table { border-spacing:0 }

        #section_information
        {
            display: grid;
            grid-template-columns: 70% 30%;
            column-gap: 3%;
        }
        #right_side {width: 40%;}
        #parent {width: 100%;}
        .movies
        {
            display:flex;
            justify-content: space-evenly;
            column-gap: 5%;
            row-gap: 20px;
            flex-basis: 50%;
            flex-wrap: wrap;
            flex-direction: row;
            margin-top: 5%;
        }   
    </style>
{% endblock %}

{% block content %}

<div id = "webpage">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id = "header">
        <div class="collapse navbar-collapse" id="navbarScroll">
          <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home' %}">
                <button type="button" class="btn btn-light position-relative">
                    Home
                </button>
            </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Movies' %}">
                <button type="button" class="btn btn-light position-relative">
                    Movies
                </button>
            </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Directors' %}">
                    <button type="button" class="btn btn-primary position-relative">
                        Directors
                    </button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#section_name">
                    <button type="button" class="btn btn-secondary position-relative">
                        {{ director.name }}
                    </button>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Actors' %}">
                    <button type="button" class="btn btn-light position-relative">
                        Actors
                    </button>
                </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarScrollingDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                <button type="button" class="btn btn-info position-relative">
                    Account
                </button>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                {% if user.username != "" %}
                    <li><a class="dropdown-item" href="{% url 'Profile' %}">{{ user.username }}</a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{% url 'Logout' %}">Logout</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url 'Register' %}">Register</a></li>
                    <li><a class="dropdown-item" href="{% url 'Login' %}">Login</a></li>
                {% endif %}
              </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'Suggest' %}">
                    <button type="button" class="btn btn-warning position-relative">
                        Suggest
                    </button>
                </a>
            </li>
          </ul>
          <!-- <form class="d-flex">
            <input class="form-control mr-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form> -->
        </div>
    </nav>

    <div id = "section_name">
        {{ director.name }}
    </div>
    <br>

    <div id = "page">

        <div id = "right_side">
            <div class = "section_separator">
                MOVIES
            </div>
            
            <div class = "movies">
                {% for movie in director.movie_set.all %}
                    <div class = "images" style = "width: 30%;height: auto;">
                        <a href = "{% url 'MoviesDetail' movie.id %}" target = "_blank">
                            <img src="{{ movie.image.url }}" style="width: 100%; height: auto"> 
                        </a>
                        <figcaption style = "text-align: center;"> {{ movie.name }} </figcaption>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div id = "parent">

            <div class = "section_separator">
                INFORMATION
            </div>
            <br>
        
            <div id = "section_information">

                <div style = "display: flex;align-items: center;">
                    {{ director.review }}
                </div>

                <div class = "images" style = "width: 70%;height: auto">
                    <img src="{{ director.image.url }}" style="width: 100%;height:auto">
                    <figcaption style = "text-align: center;"> {{ director.name }} </figcaption>
                </div>
            </div>
            <br>

            <div class = "section_separator">
                STATISTICS
            </div>
            <br>
            
            <div>
                <table class = "table" style = "width: 100%">
                    <thead>
                        <form method = "POST">{% csrf_token %}
                            <th style = "text-align: center;">Year<input name = "Year" type = "checkbox"></th>
                            <th style = "text-align: center;">Movies<input name = "Movie" type = "checkbox"></th>
                            <th style = "text-align: center;">Our Score<input name = "Our_score" type = "checkbox"></th>
                            <th style = "text-align: center;">Rotten Tomatoes<input name = "Rotten" type = "checkbox"></th>
                            <th style = "text-align: center;">Imdb<input name = "imdb" type = "checkbox"></th>
                        </form>
                    </thead>
                    <tbody>
                        {% for movie in movie_list %}
                            <tr>
                                <td>{{ movie.only_year }}</td>
                                <td><a href = "{% url 'MoviesDetail' movie.id %}">{{ movie.name }}</a></td>
                                <td>{{ movie.final_score }}</td>
                                <td>{{ movie.rotten_tomatoes }}</td>
                                <td>{{ movie.imdb }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

    </div>

    <div id = "bottom" class = "bg-dark">
    </div>  
</div>


{% endblock %}

{% block scripts %}

{{ applied_filters|json_script:'applied_filters' }}
<script src = "{% static 'blog/js/jquery.js' %}"></script>
<script>
   
    var applied_filters = jQuery.parseJSON($("#applied_filters").text())
    var inputs = $("input");

    console.log(applied_filters)

    for (input of inputs)
    {
        for (filter of applied_filters)
        {
            if (input.name == filter)
            {
                console.log(input.name)
                $(input).prop("checked",true)
            }else{
                $(input).css("display","None")
            }
        }
    }

    for (input of inputs)
    {
        $(input).change(function(){
            console.log(this.name)
            this.form.submit()
        })
    } 
    
</script>

{% endblock %}